### ISSUE TITLE
I get these errors in pixeldraw:

### ISSUE THREAD

**Issue by AstroNaut244** [justinjohn0306/VQGAN-CLIP#10]
iter: 0, loss: 2.74, losses: 0.985, 0.882, 0.876 (-0=>2.743)
Oops: runtime error:  radix_sort: failed on 1st step: cudaErrorInvalidDeviceFunction: invalid device function
Try reducing --num-cuts to save memory
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-9e66114ed510> in <module>()
     45 settings = pixray.apply_settings()
     46 pixray.do_init(settings)
---> 47 pixray.do_run(settings)
     48 #@markdown ---

6 frames
/usr/local/lib/python3.7/dist-packages/diffvg-0.0.1-py3.7-linux-x86_64.egg/pydiffvg/render_pytorch.py in backward(ctx, grad_img)
    707                       use_prefiltering,
    708                       diffvg.float_ptr(eval_positions.data_ptr()),
--> 709                       eval_positions.shape[0])
    710         time_elapsed = time.time() - start
    711         global print_timing

RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDeviceFunction: invalid device function

and

AttributeError                            Traceback (most recent call last)
<ipython-input-3-9e66114ed510> in <module>()
     32 
     33 # these are good settings for pixeldraw
---> 34 pixray.reset_settings()
     35 pixray.add_settings(prompts=prompts, aspect=aspect)
     36 pixray.add_settings(quality="better", scale=2.5)

AttributeError: module 'pixray' has no attribute 'reset_settings'

**Comment by justinjohn0306** [comment]
You'll need Tesla T4 or higher GPU for this to work
