### ISSUE TITLE
hi bro i need your help please reply

### ISSUE THREAD

**Issue by jsdnjn** [justinjohn0306/VQGAN-CLIP#2]

**Comment by justinjohn0306** [comment]
Hi, what kind of help are you looking for?

**Comment by jsdnjn** [comment]
i want to set up a github action which ssh into a server ( say colab) and executes given command, could you help me , i found some repo which do the same but i have to change the port and hostname everytime by going in secrets, is there any way i can set them at workflow_dispatch
