### ISSUE TITLE
Message on downloading models part says "Could not resolve host: mirror.io.community" which makes the execution fail.

### ISSUE THREAD

**Issue by whyiseverythingbad** [justinjohn0306/VQGAN-CLIP#7]
Message on downloading models part says "Could not resolve host: mirror.io.community" which makes the execution fail. When it used to work, you'd press download model and it would give you a whole message saying the time left and how much time it has already been working, etc. Now the download finishes in less than a second and the only thing it says is "Message on downloading models part says "Could not resolve host: mirror.io.community" which makes the execution fail."
I've tried multiple different versions of the same code, different accounts, reset it multiple times, still to no avail. Almost all of the models don't work besides celebahq I think. I've been doing the same thing for almost a month now, and just a couple days ago it started to not work.
I have no idea what's happening. I'm doing everything right. Please fix this!!!
Pictures included is the failed execution and the main message I'm talking about. Also my GPU.
<img width="712" alt="screenshot 2021-08-22 at 13 13 59" src="https://user-images.githubusercontent.com/87880223/130365589-41284891-f18c-49c7-9855-00361cc90c67.png">

<img width="1429" alt="screenshot 2021-08-22 at 13 13 17" src="https://user-images.githubusercontent.com/87880223/130365573-a0878852-59c2-400f-bab9-dae27a4f6550.png">

<img width="1378" alt="screenshot 2021-08-22 at 13 10 14" src="https://user-images.githubusercontent.com/87880223/130365509-940f283b-1e09-45a4-a5f1-70a33bacf59b.png">

**Comment by justinjohn0306** [comment]
Updated imagenet model links and it should be working now
